config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "dashboard", to: "pages#dashboard"
  get "profile/:user_id", to: "pages#profile", as: :profile # missing ID
  get "account", to: "pages#account", as: :account
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :sport_events do
    resources :requests, only: [:index, :new, :create]
    resources :reviews, only: [:create]
    resources :messages, only: [:create]
    member do
      get "chat"
    end
  end
  patch "requests/:id", to: "requests#accept", as: :accept_request
  # patch "requests/:id", to: "requests#cancel", as: :cancel_request
  resources :requests, only: [:destroy]
end

app/models/sport_event.rb
class SportEvent < ApplicationRecord
  SPORTS = %w[Football Basketball Tennis Golf Volleyball TableTennis Badminton Beerpong]
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  belongs_to :user
  has_many :users, through: :requests
  has_many :reviews, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :requests, dependent: :destroy
  validates :address, presence: true
  validates :start_at, presence: true
  validates :sport, presence: true
  validates :sport, inclusion: { in: SPORTS }
  has_one_attached :photo

  def city_name
    address.split(",").first
  end
end

app/controllers/sport_events_controller.rb
class SportEventsController < ApplicationController
  def index
    if params[:query].present?
      session[:query] = params[:query]
      @sport_events = SportEvent.where("address ILIKE ?", "%#{params[:query]}%")
      # @sport_events = @sql_results.select { |sport_event| sport_event.user != current_user }
    elsif params[:sport_event] && params[:sport_event][:sport].present? && session[:query].present?
      @sport_events = SportEvent.where("sport ILIKE :sport AND address ILIKE :location", sport: "%#{params[:sport_event][:sport]}%", location: "%#{session[:query]}%")
    elsif params[:sport_event] && params[:sport_event][:sport].present?
      @sport_events = SportEvent.where("sport ILIKE ?", "%#{params[:sport_event][:sport]}%")
    else
      @sport_events = SportEvent.all
    end
  end

  def show
    @sport_event = SportEvent.find(params[:id])
    @request = Request.new
    @user_request = Request.find_by(user: current_user, sport_event: @sport_event)
    @user_ids = @sport_event.requests.where(accepted: true).pluck(:user_id)
    @users = User.where(id: @user_ids)

    # @message = Message.new
    @review = Review.new
  end

  def new
    @sport_event = SportEvent.new
  end

  def create
    @sport_event = SportEvent.new(sport_event_params)
    @sport_event.sport.capitalize!
    @sport_event.user = current_user

    unless @sport_event.photo.attached?
      # @result = Cloudinary::Uploader.upload("my_image.jpg")
      # @sport_event.image = cl_image_path @sport_event.image.key
      @sport_event.image = "https://res.cloudinary.com/dc5dpsxvz/image/upload/v1678396659/SweatSquad/#{@sport_event.sport}#{rand(1..3)}.jpg"
    end#
    
    if @sport_event.save
      redirect_to sport_event_path(@sport_event)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @sport_event = SportEvent.find(params[:id])
  end

  def update
    @sport_event = SportEvent.find(params[:id])
    @sport_event.update(sport_event_params)
    if @sport_event.save
      redirect_to sport_event_path(@sport_event)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @sport_event = SportEvent.find(params[:id])
    @sport_event.destroy
    redirect_to sport_events_path, status: :see_other
  end

  def chat
    @sport_event = SportEvent.find(params[:id])
    @messages = @sport_event.messages
    @message = Message.new
  end

  private

  def sport_event_params
    params.require(:sport_event).permit(:address, :start_at, :sport, :description, :photo)
  end
end

app/views/sport_events/chat.html.erb
<div class="">
  <div class="container chatroom" data-controller="sport-event-subscription" data-sport-event-subscription-sport-event-id-value="<%= @sport_event.id %>" data-sport-event-subscription-current-user-id-value="<%= current_user.id %>">
    <h1>#<%= @sport_event.sport %></h1>

    <div class="messages" data-sport-event-subscription-target="messages">
      <% @sport_event.messages.each do |message| %>
        <div class="message-row d-flex <%= message.sender?(current_user) ? 'justify-content-end' : 'justify-content-start' %>">
          <div class="<%= message.sender?(current_user) ? 'sender-style' : 'receiver-style' %>">
            <%= render "messages/message", message: message %>
          </div>
        </div>
      <% end %>
    </div>
    <%= simple_form_for [@sport_event, @message],
      html: { data: { action: "turbo:submit-end->sport-event-subscription#resetForm" }, class: "d-flex"} do |f|
    %>
      <%= f.input :content,
        label: false,
        placeholder: "Message ##{@sport_event.sport}",
        wrapper_html: {class: "flex-grow-1"}
      %>
      <%= f.submit "Send", class: "btn btn-primary mb-3" %>
    <% end %>
  </div>
</div>

app/views/sport_events/edit.html.erb
<hr>
<center><h1>Edit/Update Event</h1></center>
<hr>

<div class= "container">
  <%= simple_form_for(@sport_event) do |f| %>
    <%= f.input :address %>
    <%= f.input :sport %>
    <%= f.input :description %>
    <%= f.input :start_at %>
  <div>
    <hr>
    <center><%= f.submit %></center>
    <hr>
  </div>
  <% end %>
</div>

app/views/sport_events/index.html.erb
<%= simple_form_for :sport_event, method: :get, url: sport_events_path do |f| %>
 <%= f.input :sport, prompt: "Choose your sport", collection: SportEvent::SPORTS, label: false %>
 <%= f.button :submit, class: "btn btn-primary btn-block", style: "width: 100%;", value: "Apply sport filter" %>
<% end %>
<hr>
<center><h1 class="h1-headers">Current Events Available</h1></center>
<hr>
<div class= "cards">
  <% @sport_events.each do |event| %>

    <%=  link_to sport_event_path(event), class: "text-decoration-none" do %>
      <div class="card-wrapper text-decoration-none">
        <div class="card">
          <div class="card-img" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= event.photo.attached? ? cl_image_path(event.photo.key) : event.image %>);">
            <h5><i class="showpage-icons fa-solid fa-location-dot"></i><%= event.address %></h5>
            <h3 class="text-decoration-transparent"><%= event.sport %></h3>
          </div>

          <div class="card-details">
            <div class="img-username">
              <% if event.user.photo.attached? %>
                <%= cl_image_tag(event.user.photo.key, :class => "avatar") %>
              <% else %>
                <img class="avatar-large" alt="avatar-large" src=<%= asset_path "avatar.png"%> />
              <% end %>
              <p><%= event.user.username %></p>
            </div>

            <div class="date-location">
              <h5><i class="showpage-icons fa-regular fa-calendar-days"></i><%= event.start_at.strftime("%d %B") %></h5> <%# needs some polishing  %>
              <h5><i class="showpage-icons fa-regular fa-clock"></i><%= event.start_at.strftime("%H:%M") %></h5>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>
<br>
<br>

app/views/sport_events/new.html.erb
<hr>
  <center><h1>Create an Event</h1></center>
<hr>
<div class= "container">
  <%= simple_form_for @sport_event, data: { controller: 'flatpickr' } do |f| %>
    <%= f.input :address, label: false,
      input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
      wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}} %>
      <hr>
    <%= f.input :sport, label: false, collection: SportEvent::SPORTS, prompt: "Choose your sport" %>
      <hr>
    <%= f.input :description, label: false, placeholder: "Short description about your sport event" %>
      <hr>
    <%= f.input :start_at, label: false, as: :string, input_html: { data: { flatpickr_target: "startAt" } }, placeholder: "Select date and time for your event" %>
      <hr>
    <%= f.input :photo, as: :file %>
    <hr>
    <%= f.submit class: "btn btn-primary w-100" %>
  <% end %>
</div>

app/views/sport_events/show.html.erb
<div class="card-trip">
  <div class="show-img" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= @sport_event.photo.attached? ? cl_image_path(@sport_event.photo.key) : @sport_event.image %>)">
    <h5 class="mb-2"><i class="showpage-icons fa-solid fa-location-dot"></i>  <%= @sport_event.address.first(20) %>...</h5>
  </div>

  <div class="card-trip-infos py-5">
    <div class="d-flex justify-content-around">
      <h4 class="card-trip-pricing"><i class="showpage-icons fa-regular fa-calendar-days"></i><%= @sport_event.start_at.strftime("%d %B") %></h4>
      <h4 class="card-trip-pricing"><i class="showpage-icons fa-regular fa-clock"></i><%= @sport_event.start_at.strftime("%H %M") %></h4>
    </div>

    <div class="d-flex flex-column align-items-center text-break">
      <h2><%= @sport_event.sport %></h2>
      <p><%= @sport_event.description %></p>
    </div>

    <%= link_to profile_path(@sport_event.user) do %>
      <% if @sport_event.user.photo.attached? %>
        <%= cl_image_tag(@sport_event.user.photo.key, :class => "reviewer-pic avatar-bordered") %>
      <% else %>
        <img class="reviewer-pic avatar-bordered" alt="avatar-large" src=<%= asset_path "avatar.png"%> />
      <% end %>
    <% end %>
  </div>
</div>

<div class= "container">
    <%# <% raise %>
  <% if current_user != @sport_event.user && (@user_request.nil?) %>
    <%# display only if the user hasnt sent a request yet %>
    <div class="my-3">
      <%= simple_form_for [@sport_event, @request] do |f| %>
        <%= f.input :message, placeholder: "Write a message to #{@sport_event.user.username}...", label: false, as: :text %>
        <%= f.button :submit, "Request to join", class: "btn btn-primary w-100" %>
      <% end %>
    </div>
  <% elsif @user_request&.accepted == false %>
    <div class="text-center mt-2">
      <h2>Request pending</h2>
    </div>
  <% elsif @user_request&.accepted == true %>
    <div class= "container">
      <% if current_user != @sport_event.user && @user_request &&  !current_user.review_given?(@sport_event) %>
        <%= simple_form_for [@sport_event, @review] do |f| %>
          <%= f.input :rating,label: false, placeholder: "Give #{@sport_event.user.username} a rating 1 - 5", input_html: { class: "my-3"} %>
          <%# <br> %>
          <%= f.input :content,label: false, placeholder: "Tell us about your experience with #{@sport_event.user.username}", input_html: { class: "my-3"} %>
          <center><%= f.button :submit, "Create a review", class: 'btn btn-success' %></center>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>
<% if current_user == @sport_event.user || @user_request&.accepted == true %>
  <%= link_to "#{@sport_event.sport} chatroom", chat_sport_event_path(@sport_event), class: "btn btn-primary w-100 my-3" %>
<% end %>



<div class= "showpage-edit-delete-btns mb-5">
  <% if current_user == @sport_event.user %>
    <%= link_to "Update", edit_sport_event_path(@sport_event), class: 'btn btn-success' %>
    <%= link_to 'Delete', @sport_event, data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this event?" }, class: 'btn btn-danger' %>
  <% else %>
    <%# <%= link_to "Request to join", sport_event_requests_path(@sport_event), class: 'btn btn-success' %>
  <% end %>
</div>
<br>
<br>