config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "dashboard", to: "pages#dashboard"
  get "profile/:user_id", to: "pages#profile", as: :profile # missing ID
  get "account", to: "pages#account", as: :account
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :sport_events do
    resources :requests, only: [:index, :new, :create]
    resources :reviews, only: [:create]
    resources :messages, only: [:create]
    member do
      get "chat"
    end
  end
  patch "requests/:id", to: "requests#accept", as: :accept_request
  # patch "requests/:id", to: "requests#cancel", as: :cancel_request
  resources :requests, only: [:destroy]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_info_window.html.erb
<h1><%= link_to sport_event.sport, sport_event_path(sport_event), class: "text-decoration-none text-dark" %></h1>

app/views/shared/_marker.html.erb
<%= image_tag "checkpoint1.png", height: 30, width: 30, alt: "Logo" %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar_bottom.html.erb
<% if current_user %>
  <div class="navfooter">
    <div class="flex-container">
        <%= link_to dashboard_path do %><i class="navfooter-links fa-solid fa-gauge"></i><% end %>
        <%= link_to sport_events_path do %><i class="navfooter-links fa-solid fa-list"></i><% end %>
        <%= link_to new_sport_event_path do %><i class="navfooter-links fa-solid fa-circle-plus"></i><% end %>
        <%= link_to profile_path(current_user) do %><i class="navfooter-links fa-regular fa-user"></i><% end %>
    </div>
  </div>
<% end %>

app/views/shared/_new_navbar.html.erb
<div class="navbar navbar-expand-lg navbar-light bg-blue">
  <div class="container-fluid">
    <div class="navbar-nav me-auto mb-2 mb-lg-0 back">
      <%= link_to '<i class="fa-solid fa-chevron-left"></i>'.html_safe, :back, class: "nav-link" %>
    </div>

    <div>

    </div>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        </li>
      </ul>

    <div class="navbar-nav me-right mb-2 mb-lg-0">
      <%= link_to '<i class="fa-solid fa-arrow-right-from-bracket"></i>'.html_safe, "/users/sign_out", class: "nav-link", data: {turbo_method: :delete} %>
    </div>

    <ul class="navbar-nav me-right mb-2 mb-lg-0">
      <li class="nav-item">
        <%=link_to "Log out", "/users/sign_out", class: "nav-link", data: {turbo_method: :delete} %>
        <img src="" alt="">
        <%=link_to "Home", :root, class: "nav-link" %>
      </li>
    </ul>


  </div>
</div>

app/views/shared/_top_navbar.html.erb
<div class="navbar px-3">
  <%#= link_to '<i class="fa-solid fa-chevron-left"></i>'.html_safe, :back, class: "nav-link" %>
   <%= link_to '<i class="fa-solid fa-chevron-left"></i>'.html_safe, 'javascript:history.back()', class: "nav-link" %>
  <%= link_to :root do %>
    <img src="<%= asset_path "Logo_green.png"%>" alt="" width="40px">
  <% end %>
  <% if user_signed_in? %>
    <%= link_to '<i class="fa-solid fa-arrow-right-from-bracket"></i>'.html_safe, "/users/sign_out", class: "nav-link", data: {turbo_method: :delete} %>
  <% else %>
    <%= link_to '<i class="fa-solid fa-right-to-bracket"></i>'.html_safe, new_user_session_path, class: "nav-link" %>
  <% end %>
</div>