config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "dashboard", to: "pages#dashboard"
  get "profile/:user_id", to: "pages#profile", as: :profile # missing ID
  get "account", to: "pages#account", as: :account
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :sport_events do
    resources :requests, only: [:index, :new, :create]
    resources :reviews, only: [:create]
    resources :messages, only: [:create]
    member do
      get "chat"
    end
  end
  patch "requests/:id", to: "requests#accept", as: :accept_request
  # patch "requests/:id", to: "requests#cancel", as: :cancel_request
  resources :requests, only: [:destroy]
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :sport_event
  validates :message, presence: true
  # validates :user_id, uniqueness: {
  #  scope: :sport_event_id,
  #  message: "You have already requested to join this event. Wait for the host to accept your request."
  # }
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  def index
    @sport_event = SportEvent.find(params[:sport_event_id])
    @requests = Request.where(sport_event: @sport_event, accepted: false)
  end

  def new
    @request = Request.new
  end

  def create
    @sport_event = SportEvent.find(params[:sport_event_id])
    @request = Request.new(request_params)
    @request.user = current_user
    @request.sport_event = @sport_event
    @message = Message.new
    @review = Review.new # for the render
    if @request.save
      redirect_to sport_event_path(@request.sport_event), notice: "Request sent"
    else
      render "sport_events/show", status: :unprocessable_entity
    end
    # raise
  end

  def accept
    @request = Request.find(params[:id])
    if @request.accepted == false
      @request.accepted = true
      @request.save
      redirect_to sport_event_requests_path(@request.sport_event), notice: "You have accepted the request"
    else
      @request.accepted = false
      @request.save
      redirect_to sport_event_requests_path(@request.sport_event), notice: "You have declined the request"
    end
  end

  # NEEDS TO BE FIXED
  # def cancel
  #   @request = Request.find(params[:id])
  #   @request.accepted = false
  #   @request.save
  #   redirect_to dashboard_path, status: :see_other
  # end

  def destroy
    @request = Request.find(params[:id])
    @sport_event = @request.sport_event
    @request.destroy
    redirect_to sport_event_requests_path(@sport_event), status: :see_other, notice: "You have declined the request"
  end

  private

  def request_params
    params.require(:request).permit(:message)
  end
end

app/views/requests/index.html.erb
<center><h1>Requests for this event</h1></center>
<% @requests.each do |request| %>
  <%=  link_to profile_path(request.user), class: "text-decoration-none text-dark" do %>
    <div class="review-container my-4">
      <div class="review-info">
        <div class="image-username-rating">
          <div class="review-img">
            <% if request.user.photo.attached? %>
              <%= cl_image_tag(request.user.photo.key, :class => "reviewer-pic") %>
            <% else %>
              <img class="reviewer-pic" alt="avatar-large" src=<%= asset_path "avatar.png"%> />
            <% end %>
          </div>
          <div class="user-name">
            <h3><%= request.user.username %></h3>
          </div>
        </div>

        <div class="user-review-date">
          <p><%= request.created_at.strftime("%d %B") %></p>
          <p><%= request.sport_event.sport %></p>
        </div>
      </div>

      <div class="review-content mt-3 p-1 text-break">
        <p class="m-1"><%= request.message %></p>
      </div>

       <div>
        <center><%= link_to '<i class="fa-solid fa-x"></i>'.html_safe, accept_request_path(request), data: { turbo_method: :delete }, style: "color: red;",  class: "mx-3" %>
        <%= link_to '<i class="fa-solid fa-check"></i>'.html_safe, accept_request_path(request), data: { turbo_method: :patch }, style: "color: green;" %></center>
      </div>
    </div>
  <% end %>
<% end %>